source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '5.0.0'
gem 'pg'
gem 'puma'
gem 'sass-rails'
gem 'compass-rails', github: 'Compass/compass-rails', branch: 'master'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', :git => 'git://github.com/twalpole/devise.git'
gem 'cancancan', '~> 1.10.1'
gem 'role_model'
gem 'paperclip', :git => 'git://github.com/thoughtbot/paperclip.git'
gem 'rmagick'
gem 'react_on_rails'
gem 'rails_admin', '>= 1.0.0.rc'
gem 'mini_racer', platforms: :ruby
gem 'pdf-reader'
gem 'aws-sdk', '~> 2.0'
gem 'pdfjs_viewer-rails', '0.0.9', :path => 'vendor/gems/pdfjs_viewer-rails-0.0.9'
gem 'redis', '~> 3.0'
gem 'sidekiq', '4.1.2'
gem 'sidekiq-failures'
gem 'sidekiq_mailer'
gem 'sidekiq-statistic'
gem 'sidekiq-unique-jobs', '4.0.17'
gem 'sinatra', github: 'sinatra'
gem 'fog'
gem 'mini_magick'
gem 'carrierwave_direct'
gem 'jquery-fileupload-rails', '~> 0.4.1'
gem 'font-awesome-rails'
gem 'bugsnag'
gem 'omniauth-google-oauth2'
gem 'google-api-client', '0.8.2', require: 'google/api_client'
gem 'rest-client'
gem 'clearbit'
gem 'facebook-messenger', '0.8.0'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'better_errors'
  gem 'bullet'
  gem 'foreman'
  gem 'lol_dba'
  gem 'memory_profiler'
  gem 'pghero'
  gem 'powder'
  gem 'rails-footnotes'
  gem 'rubocop'
  gem 'ruby-prof'
  gem 'squasher'
  gem 'web-console'
  gem 'jazzhands'
end

group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'fixture_builder'
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'rspec-context-private'
  gem 'rspec-sidekiq'
  gem 'rspec-core'
  gem 'shoulda-callback-matchers'
  gem 'launchy'
  gem 'timecop'
  gem 'faker'
end
